### ISSUE TITLE
Not working in my project

### ISSUE THREAD

**Issue by wolfsmith520-github** [3ddelano/discord.gd#19]
Still work ?

**Comment by newjoker6** [comment]
It appears not, so I am guessing something was changed on discord's end. Since it is getting close to two years since the last update, I wouldn't hold out hope for an update. This means you will need to either read discord's documentation and try to connect it yourself, or maybe find an alternative plugin to accomplish this.

**Comment by 3ddelano** [comment]
I just checked the sample project and its working fine for me using text commands.
