### ISSUE TITLE
Reactions

### ISSUE THREAD

**Issue by KenneyNL** [3ddelano/discord.gd#5]
Hey, I was wondering if it'd be possible for a bot to add a reaction to a message? That'd be a great addition, thanks :)

**Comment by 3ddelano** [comment]
I've tried to implement reactions but sadly Godot doesn't support emoji characters. The current option is to use buttons. Maybe in Godot 4 emojis will be supported.

**Comment by 3ddelano** [comment]
Custom reactions support is added, this was the commit [a069bf1](https://github.com/3ddelano/discord.gd/commit/a069bf1b2e203ff164cf912d6ef0a6687965d1ea) and here is the release [Release 1.1.7](https://github.com/3ddelano/discord.gd/releases/tag/1.1.7)

**Comment by KenneyNL** [comment]
That's fantastic, thank you very much!

**Comment by stephannv** [comment]
@3ddelano did you try using `:smile:` instead `😄`? Maybe you need to add a `\` before emoji code. eg. `\:smile`

**Comment by 3ddelano** [comment]
> @3ddelano did you try using `:smile:` instead `😄`? Maybe you need to add a `\` before emoji code. eg. `\:smile`

I did try that, but the issue is that Discord expects the emoji to be in Unicode, which is completely fine. But Godot can't URl encode unicode emojis. Thus it can't make the PUT request. I tried some some emojis like the heart emoji works but others don't work. So I have currently limited to only custom emojis. Once you upload the emojis you need, you can use from any bot. Even animated emojis work.
Here is an animated parrot: bot.create_reaction(message, "565171769187500032")
More examples here: [Reaction Examples](https://github.com/3ddelano/discord.gd/wiki/Documentation#examples-12)
